branches:
  only:
    - master
    
environment:
  NETLIFY_TOKEN:
    secure: NAVUlhHdM/Kn0YVwowLhVdUGKFgD8U5Prsn5Yacn+nPasyhNH6Oi9NXApDhdJOyE9fgGJhW75oJ0zLOIFC0d1BRGnTRUndEesWCW5/HoxCA=

# Temporarily needed until curl added to PATH
# See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
# And https://github.com/appveyor/ci/issues/1431
install:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

build_script:
  - ps: .\build.ps1 -Target "AppVeyor"
  